# syntax=docker/dockerfile:1

FROM mcr.microsoft.com/dotnet/sdk:6.0 as build-env
WORKDIR /DissertationEnviroment
COPY DissertationEnviroment/BehavioursIntegrationConnectGOOGLE.csproj .
RUN dotnet restore
COPY DissertationEnviroment .
RUN dotnet bin/Debug -c Release -o /bin/Debug

FROM mcr.microsoft.com/dotnet/aspnet:6.0 as runtime
WORKDIR /bin/Debug
COPY --from=build-env /bin/Debug .
EXPOSE 80
ENTRYPOINT ["dotnet", "BehavioursIntegrationConnectGOOGLE.dll"]