version: 2.1
jobs:
  build:
    docker:
      - image: cristircr/selenium:latest
    steps:
      - checkout
      - run:
          name: Run Selenium Tests
          command: |
            dotnet test ".\TravisSelenium\DissertationEnviroment\BehavioursIntegrationConnectGOOGLE.sln" -c Debug -v n
      - store_artifacts:
          path: bin/Release
          destination: .circleci
services:
  mcr.microsoft.com/dotnet/aspnet:6.0:
    build: .
    depends_on:
      - mcr.microsoft.com/dotnet/sdk:6.0
 
workflows:
  version: 2
  full:
    jobs:
      - build