version: 2.1
jobs:
  build:
    docker:
      - image: cristircr/selenium:latest
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
    steps:
      - checkout
      - run:
          name: Run Tests
          command: |
            docker run -d -p 5000:80 --name selenium cristircr/selenium
      - store_artifacts:
          path: bin/Release
          destination: .circleci

workflows:
  version: 2
  full:
    jobs:
      - build