version: 2.1
jobs:
  build:
    docker:
      - image: cristircr/selenium:latest
    steps:
      - checkout
      - run:
          name: Run Selenium Tests
          command: |
            dotnet DissertationEnviroment/BehavioursIntegrationConnectGOOGLE.dll
      - store_artifacts:
          path: bin/Release
          destination: .circleci

workflows:
  version: 2
  full:
    jobs:
      - build