version: 2.1
jobs:
  build:
    docker:
      - image: cristircr/selenium:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            winget install --id Microsoft.VisualStudio.2019.Community
      - run:
          name: Run Selenium Tests
          command: |
           dotnet vstest "bin/Debug/BehavioursIntegrationConnectGOOGLE.dll" -t
      - store_artifacts:
          path: bin/Release
          destination: .circleci
services:
  mcr.microsoft.com/dotnet/framework/sdk:4.8:
  mcr.microsoft.com/dotnet/framework/aspnet:4.8:
    build: .
    depends_on:
      - mcr.microsoft.com/dotnet/framework/sdk:4.8
 
workflows:
  version: 2
  full:
    jobs:
      - build