version: 2.1
orbs:
  win: circleci/windows@5.0
jobs:
  pre:
    executor: win/default
    steps:
      - run: dotnet tool install --global PowerShell
  build:
    docker:
      - image: cristircr/selenium:latest
    steps:
      - checkout
      - run:
          name: Run Selenium Tests
          command: |
           apt update && apt install -qy --no-install-recommends mono-runtime libfsharp-core4.3-cil
           dotnet test "bin/Debug/BehavioursIntegrationConnectGOOGLE.dll" --filter "CBT_NUnit.CBTAPI.Initialize" --no-restore
      - store_artifacts:
          path: bin/Release
          destination: .circleci

services:
  mcr.microsoft.com/dotnet/sdk:6.0:
  mcr.microsoft.com/dotnet/aspnet:6.0:
    build: .
    depends_on:
      - mcr.microsoft.com/dotnet/sdk:6.0
workflows:
  version: 2
  full:
    jobs:
      - pre
      - build:
          requires:
            - pre