# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  go: circleci/go@1.7.1
  docker: circleci/docker@1.0.0
executors:
  dotnet-executor:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build-and-test:
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    
    executor: dotnet-executor
    steps:
      - checkout
      - run:
          name: Restore NuGet Packages
          command: dotnet restore

      - run:
          name: Build Solution
          command: dotnet build

      - run:
          name: Run Unit Tests
          command: dotnet test -- dissertation-environment~BehavioursIntegrationConnectGOOGLE

      - run:
          name: Run Selenium Tests
          command: dotnet test -- dissertation-environment~BehavioursIntegrationConnectGOOGLE
    build-docker-image:
      docker:
        - image: circleci/openjdk:8-jdk

      working_directory: ~/circleCI_Selenium_Demo

    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
      steps:
        - checkout
        - docker/install-docker-tools
        - setup_remote_docker:
            docker_layer_caching: true
            
        - run:

          name: Install latest version of ChromeDriver Sample

          command: |

            sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -

            sudo sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'

            sudo apt-get update

            sudo apt-get install google-chrome-unstable
            
        - run:

          name: Install latest version of ChromeDriver Sample

          command: |

            sudo wget https://chromedriver.storage.googleapis.com/2.31/chromedriver_linux64.zip

            sudo unzip -o chromedriver_linux64.zip

            sudo rm chromedriver_linux64.zip

            sudo mv chromedriver /usr/bin/

            sudo chmod 777 /usr/bin/chromedriver

            sudo apt-get install libxi6 libgconf-2-4

            sudo apt-get -y install xvfb gtk2-engines-pixbuf

            sudo apt-get -y install xfonts-cyrillic xfonts-100dpi xfonts-75dpi xfonts-base xfonts-scalable

            sudo apt-get install xvfb

            sudo apt-get -y install imagemagick x11-apps

        - run:
            name: Build and push Docker image
            command: |
              sudo apt-get purge -y curl && sudo apt-get install -y curl
              sudo curl -L "https://github.com/docker/compose/releases/download/2.17.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
              docker-compose --2.17.3
              docker build -t circleci/node:14 .
              docker login -u $CristiRcr -p $#CT02glcv
              docker push circleci/node:14

# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  #sample: # This is the name of the workflow, feel free to change it to better match your workflow.
  test-and-deploy:
    jobs:
      - build-and-test
      - build-docker-image:
          requires:
            - build-and-test