version: 2.1
jobs:
  build:
    docker:
      - image: cristircr/selenium:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            winget install --id Microsoft.VisualStudio.2019.Community
      - run:
          name: Run Selenium Tests
          command: |
            vstest.console.exe BehavioursIntegrationConnectGOOGLE.dll /TestAdapterPath:"."
      - store_artifacts:
          path: bin/Release
          destination: .circleci
          
services:
  mcr.microsoft.com/dotnet/aspnet:6.0:
    build: .
    depends_on:
      - mcr.microsoft.com/dotnet/sdk:6.0
 
workflows:
  version: 2
  full:
    jobs:
      - build